controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

remove_advert_image:
    path: '/owner/advert/remove-image/{advertId}/{imageId}'
    controller: 'App\Controller\AdvertController::removeImage'

get_adverts_json:
    path: /get-adverts-json
    controller: App\Controller\AdvertController::getAdvertsJson
