controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute


get_adverts_json:
  path: /get-adverts-json
  controller: App\Controller\AdvertController::getAdvertsJson

index:
  path: /
  controller: App\Controller\HomeController::index
